// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Product
{
    public int ProductId { get; set; }

    public int? CategoryId { get; set; }

    public string ProductName { get; set; }

    public string ProductDescription { get; set; }

    public decimal? Price { get; set; }

    public string ImagePath { get; set; }

    public virtual Category Category { get; set; }
}