// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Entities;

public partial class User
{
    public int UserId { get; set; }

    [EmailAddress, Required]
    public string UserEmail { get; set; }

    public string UserFirstName { get; set; }

    public string UserLastName { get; set; }

    [Required, StringLength(maximumLength: 8, ErrorMessage = "password must be 8 chars max"), MinLength(4)]
    public string UserPassword { get; set; }
}